# Generated by Django 5.1.4 on 2026-04-07 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityEconomicMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('base_multiplier', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='CostPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('plot_area_sqft', models.FloatField()),
                ('builtup_area_sqft', models.FloatField()),
                ('floors', models.PositiveIntegerField()),
                ('bhk', models.PositiveIntegerField()),
                ('material_tier', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=20)),
                ('soil_type', models.CharField(choices=[('Hard Rock', 'Hard Rock'), ('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Black Cotton', 'Black Cotton'), ('Loamy', 'Loamy')], max_length=40)),
                ('predicted_cost_inr', models.FloatField()),
                ('model_version', models.CharField(default='rf_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('material', models.CharField(choices=[('Cement', 'Cement'), ('Steel', 'Steel'), ('Sand', 'Sand')], max_length=30)),
                ('price_per_unit', models.FloatField()),
                ('unit', models.CharField(default='per unit', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'material'], name='core_materi_city_a072fd_idx')],
                'unique_together': {('city', 'material')},
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('signin', 'Signin')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'created_at'], name='core_otpcod_email_569ec9_idx')],
            },
        ),
    ]
