# Generated by Django 5.1.4 on 2026-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_materialmarketindex_options_floorplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
