# Generated by Django 5.1.4 on 2026-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_floorplan_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
