export const CITY_OPTIONS = [
  "Mumbai",
  "Delhi",
  "Bengaluru",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Noida",
  "Gurugram",
  "Jaipur",
  "Lucknow",
  "Chandigarh",
  "Indore",
  "Bhopal",
  "Nagpur",
  "Surat",
  "Vadodara",
  "Nashik",
  "Kochi",
  "Thiruvananthapuram",
  "Coimbatore",
  "Visakhapatnam",
  "Vijayawada",
  "Bhubaneswar",
  "Patna",
  "Ranchi",
  "Raipur",
  "Mysuru",
  "Mangalore",
];

export const MATERIAL_OPTIONS = ["Standard", "Premium", "Luxury"];
export const SOIL_OPTIONS = ["Hard Rock", "Sandy", "Clay", "Black Cotton", "Loamy"];
